### ISSUE TITLE
Is there a bug in making mask for loss？

### ISSUE THREAD

**Issue by L-Hugh** [MauritsBleeker/Bi-STET#10]
Thank you for your elegant code!
Is this a bug?
https://github.com/MauritsBleeker/Bi-STET/blob/ab83a47ef2e107dd7160ea0ca1832fa0531926b7/src/Dataset.py#L138
I think maybe it should be `return torch.from_numpy(mask[-1:, :])`.
Let me know if I'm wrong please, think you again!

**Comment by MauritsBleeker** [comment]
Hi, 

It has been a while since I worked with codebase, but I don't think this is a mistake. Probably this line is needed to fix/align some dimensions?

Let me know if you have any questions!

Maurits
