### ISSUE TITLE
Training ICDAR15

### ISSUE THREAD

**Issue by ghost** [MauritsBleeker/Bi-STET#2]
@MauritsBleeker 
Thank you for your hard work, you are appreciated,

In the case that I want to train ICDAR15:
- Which exact lines of code should I change?
- How should the dataset be structured?
Upload an example if possible

**Comment by MauritsBleeker** [comment]
Hi @deepseek,

Make an annotation file according to this format:
https://github.com/MauritsBleeker/Bi-STET#test-and-train-annotations

Next,  make two variables similar to this line: https://github.com/MauritsBleeker/Bi-STET/blob/master/src/Config.py#L37

Finally, put those two variables in a tuple similar to this line: https://github.com/MauritsBleeker/Bi-STET/blob/master/src/Config.py#L60 and comment out all the sets you don't need.

Best,
Maurits

**Comment by MauritsBleeker** [comment]
Btw, training on ICDAR15 **_only_** is not recommended. The model will overfit on this dataset.
