### ISSUE TITLE
Training icdar2015 from scratch

### ISSUE THREAD

**Issue by ghost** [MauritsBleeker/Bi-STET#5]
@MauritsBleeker 

When trying to train icdar 2015 from scratch, I get an error.
- Have a look at [changes in my fork](https://github.com/MauritsBleeker/Bi-STET/compare/master...deepseek:master).
- Download the Bi-STET that i tested on, it includes the data I used. [Bi-STET-deepseek.zip](https://github.com/MauritsBleeker/Bi-STET/files/4212263/Bi-STET-deepseek.zip)

```
(final) home@home-desktop:~/p13/Bi-STET-master/src$ python main.py
2020-02-17 09:19:39,270 root  INFO     Model created
Traceback (most recent call last):
  File "main.py", line 48, in <module>
    dataset_paths=config.VALIDATION_DATASETS,
AttributeError: 'Config' object has no attribute 'VALIDATION_DATASETS'
```

**Comment by MauritsBleeker** [comment]
https://github.com/MauritsBleeker/Bi-STET/blob/1a5b582a531b3e8d229aedf1d2d9b1ac41b42fbd/src/Config.py#L191

Can you call this function?
