### ISSUE TITLE
Training Text-Lines?

### ISSUE THREAD

**Issue by ghost** [MauritsBleeker/Bi-STET#7]
@MauritsBleeker 
Can Bi-STET be trained to recognize text-lines instead of single words?

**Comment by MauritsBleeker** [comment]
If the data is annotated as a text-line, and you add a space character to the output space. Yes!

**Comment by ghost** [comment]
@MauritsBleeker according to your paper:

> After a sequence length of 11, the accuracy starts to degrade

So if I train Bi-STET on sentences, the results would be bad?
Also, would Bi-STET  really understand each word? does changing one word in a sentence lowers the recognition rate?

**Comment by MauritsBleeker** [comment]
Bi-STET is made to predict characters not words and sentences. If you want to predict a sentence, you should change the output to either words, or add a 'space' character. With option 2 the output length becomes quite long, and therefore probably the performance will drop.
