### ISSUE TITLE
'NoneType' object has no attribute 'data'

### ISSUE THREAD

**Issue by kaiyon07** [MauritsBleeker/Bi-STET#8]
Thank you for your fascinating work.

I am facing some issues while running the code. How do I correct this?
![error](https://user-images.githubusercontent.com/35873631/80299703-079fd600-87b4-11ea-9ad8-f9d585cfc19a.PNG)

**Comment by MauritsBleeker** [comment]
I am not sure. This seems to be a Pytorch-version thing. Can you run the code in a  debugger? And inspect layer.self_attn.attn?

**Comment by kaiyon07** [comment]
I have added few changes to the model. The mean running time is pretty low, also the gpu usage was around 1.5 GB for batch_size=32 which is quite low as compared to other transformer models. 

What do you think about this is there a bug in my code?

![error2](https://user-images.githubusercontent.com/35873631/80312905-7d805d80-8805-11ea-8810-e7a5858f4965.PNG)

**Comment by MauritsBleeker** [comment]
Loss seems to be quite high. Are the validation scores okay?

**Comment by kaiyon07** [comment]
Loss is high because the length of number of output token is high. I was mainly concern about the GPU usage?

**Comment by kaiyon07** [comment]
I inspected the layer.self_attn has attributes modulelist 0,1,2,3, not attn. It seems like a version problem.
